### ISSUE TITLE
SVC support

### ISSUE THREAD

**Issue by leslie-wang** [aizvorski/h264bitstream#13]
Thanks for the wonderful work. I'm wondering if you have any plan to support SVC. If no, I'd like to contribute to it. Please let me know your thought.

**Comment by leslie-wang** [comment]
I've committed the change in my folked repo https://github.com/leslie-wang/h264bitstream. Please kindly let me know if you want me to create a pull request.

**Comment by aizvorski** [comment]
Hi @leslie-wang 

I had a look at your changes, sorry it took me so long to review them.  This looks fantastic!  Yes please a pull request.

Could you also add an example file with SVC? (preferably a tiny one, resolution/number of frames doesn't matter as long as it has the right headers)  I would like to start building a set of unit tests and this would help a lot since I don't have another source for SVC files.

Thanks!

**Comment by leslie-wang** [comment]
Sure. I'll send pull request firstly, then create another issue to check in some SVC sample videos.
